// types/skills.ts

export type Skill = {
  id: number;
  name: string;
};

export const skillSuggestion: Skill[] = [
  // ========================
  // TECHNOLOGY & DEVELOPMENT
  // ========================
  { id: 1, name: "JavaScript" },
  { id: 2, name: "TypeScript" },
  { id: 3, name: "Python" },
  { id: 4, name: "Java" },
  { id: 5, name: "C++" },
  { id: 6, name: "C#" },
  { id: 7, name: "Go" },
  { id: 8, name: "Rust" },
  { id: 9, name: "PHP" },
  { id: 10, name: "Ruby" },
  { id: 11, name: "Swift" },
  { id: 12, name: "Kotlin" },
  { id: 13, name: "SQL" },
  { id: 14, name: "NoSQL" },
  { id: 15, name: "PostgreSQL" },
  { id: 16, name: "MySQL" },
  { id: 17, name: "MongoDB" },
  { id: 18, name: "Firebase" },
  { id: 19, name: "Neo4j" },
  { id: 20, name: "Redis" },
  { id: 21, name: "React.js" },
  { id: 22, name: "Next.js" },
  { id: 23, name: "Vue.js" },
  { id: 24, name: "Angular" },
  { id: 25, name: "Svelte" },
  { id: 26, name: "Tailwind CSS" },
  { id: 27, name: "Bootstrap" },
  { id: 28, name: "Node.js" },
  { id: 29, name: "Express.js" },
  { id: 30, name: "NestJS" },
  { id: 31, name: "GraphQL" },
  { id: 32, name: "REST API Development" },
  { id: 33, name: "gRPC" },
  { id: 34, name: "Prisma ORM" },
  { id: 35, name: "Django" },
  { id: 36, name: "Flask" },
  { id: 37, name: "FastAPI" },
  { id: 38, name: "Spring Boot" },
  { id: 39, name: "ASP.NET Core" },
  { id: 40, name: "Laravel" },
  { id: 41, name: "Ruby on Rails" },
  { id: 42, name: "Vite" },
  { id: 43, name: "Webpack" },
  { id: 44, name: "DevOps" },
  { id: 45, name: "CI/CD" },
  { id: 46, name: "Docker" },
  { id: 47, name: "Kubernetes" },
  { id: 48, name: "Terraform" },
  { id: 49, name: "Ansible" },
  { id: 50, name: "Linux Administration" },
  { id: 51, name: "Windows Server" },
  { id: 52, name: "Cloud Computing" },
  { id: 53, name: "AWS" },
  { id: 54, name: "Google Cloud Platform" },
  { id: 55, name: "Microsoft Azure" },
  { id: 56, name: "Heroku" },
  { id: 57, name: "Netlify" },
  { id: 58, name: "Vercel" },
  { id: 59, name: "Cloudflare Workers" },
  { id: 60, name: "OpenAI API" },
  { id: 61, name: "LangChain" },
  { id: 62, name: "Machine Learning" },
  { id: 63, name: "Deep Learning" },
  { id: 64, name: "NLP" },
  { id: 65, name: "Computer Vision" },
  { id: 66, name: "Data Science" },
  { id: 67, name: "Data Engineering" },
  { id: 68, name: "Big Data" },
  { id: 69, name: "Apache Spark" },
  { id: 70, name: "Hadoop" },
  { id: 71, name: "Business Intelligence" },
  { id: 72, name: "Power BI" },
  { id: 73, name: "Tableau" },
  { id: 74, name: "ETL Processes" },
  { id: 75, name: "R Programming" },
  { id: 76, name: "MATLAB" },
  { id: 77, name: "Penetration Testing" },
  { id: 78, name: "Cybersecurity" },
  { id: 79, name: "Network Administration" },
  { id: 80, name: "Blockchain Development" },
  { id: 81, name: "Smart Contracts" },
  { id: 82, name: "Solidity" },
  { id: 83, name: "Web3" },
  { id: 84, name: "Game Development" },
  { id: 85, name: "Unreal Engine" },
  { id: 86, name: "Unity" },
  { id: 87, name: "3D Modeling" },
  { id: 88, name: "Blender" },
  { id: 89, name: "Augmented Reality" },
  { id: 90, name: "Virtual Reality" },
  { id: 91, name: "Internet of Things" },
  { id: 92, name: "Robotics" },
  { id: 93, name: "Embedded Systems" },
  { id: 94, name: "Microcontroller Programming" },
  { id: 95, name: "FPGA Design" },
  { id: 96, name: "CAD Design" },
  { id: 97, name: "PCB Design" },
  { id: 98, name: "Circuit Analysis" },
  { id: 99, name: "Automation Testing" },
  { id: 100, name: "Selenium" },

  // ================================
  // BUSINESS, MARKETING & MANAGEMENT
  // ================================
  { id: 101, name: "Project Management" },
  { id: 102, name: "Agile Methodology" },
  { id: 103, name: "Scrum Framework" },
  { id: 104, name: "Kanban" },
  { id: 105, name: "Business Analysis" },
  { id: 106, name: "Financial Modeling" },
  { id: 107, name: "Budgeting" },
  { id: 108, name: "Risk Management" },
  { id: 109, name: "Strategic Planning" },
  { id: 110, name: "Market Research" },
  { id: 111, name: "Sales Strategy" },
  { id: 112, name: "Negotiation Skills" },
  { id: 113, name: "Customer Relationship Management" },
  { id: 114, name: "Business Development" },
  { id: 115, name: "Entrepreneurship" },
  { id: 116, name: "Franchise Management" },
  { id: 117, name: "Digital Marketing" },
  { id: 118, name: "SEO Optimization" },
  { id: 119, name: "Social Media Marketing" },
  { id: 120, name: "Email Marketing" },
  { id: 121, name: "Content Marketing" },
  { id: 122, name: "Affiliate Marketing" },
  { id: 123, name: "Brand Management" },
  { id: 124, name: "Public Relations" },
  { id: 125, name: "Event Management" },
  { id: 126, name: "Copywriting" },
  { id: 127, name: "Advertising" },
  { id: 128, name: "Google Ads" },
  { id: 129, name: "Facebook Ads" },
  { id: 130, name: "Influencer Marketing" },
  { id: 131, name: "E-commerce Management" },
  { id: 132, name: "Shopify Development" },
  { id: 133, name: "Dropshipping" },
  { id: 134, name: "Customer Support" },
  { id: 135, name: "CRM Software" },
  { id: 136, name: "Data-Driven Decision Making" },
  { id: 137, name: "Team Leadership" },
  { id: 138, name: "Remote Team Management" },
  { id: 139, name: "Performance Reviews" },
  { id: 140, name: "Employee Training" },
  { id: 141, name: "Conflict Resolution" },
  { id: 142, name: "Time Management" },
  { id: 143, name: "Product Management" },
  { id: 144, name: "Product Roadmapping" },
  { id: 145, name: "Lean Startup" },
  { id: 146, name: "Business Writing" },
  { id: 147, name: "Report Writing" },
  { id: 148, name: "Presentation Skills" },
  { id: 149, name: "Pitch Deck Creation" },
  { id: 150, name: "Investor Relations" },
  { id: 151, name: "Fundraising" },
  { id: 152, name: "Venture Capital" },
  { id: 153, name: "Crowdfunding" },
  { id: 154, name: "Financial Planning" },
  { id: 155, name: "Tax Planning" },
  { id: 156, name: "Bookkeeping" },
  { id: 157, name: "Accounting" },
  { id: 158, name: "Payroll Management" },
  { id: 159, name: "Audit Preparation" },
  { id: 160, name: "Compliance" },
  { id: 161, name: "Quality Assurance" },
  { id: 162, name: "Six Sigma" },
  { id: 163, name: "Process Improvement" },
  { id: 164, name: "Change Management" },
  { id: 165, name: "Supply Chain Management" },
  { id: 166, name: "Inventory Management" },
  { id: 167, name: "Logistics Management" },
  { id: 168, name: "Procurement" },
  { id: 169, name: "Vendor Management" },
  { id: 170, name: "Export/Import Management" },
  { id: 171, name: "Retail Management" },
  { id: 172, name: "Merchandising" },
  { id: 173, name: "Product Sourcing" },
  { id: 174, name: "Customer Experience Design" },
  { id: 175, name: "Service Design" },
  { id: 176, name: "Innovation Management" },
  { id: 177, name: "Knowledge Management" },
  { id: 178, name: "Organizational Behavior" },
  { id: 179, name: "Human Resources" },
  { id: 180, name: "Talent Acquisition" },
  { id: 181, name: "Onboarding" },
  { id: 182, name: "Succession Planning" },
  { id: 183, name: "Employee Engagement" },
  { id: 184, name: "Workplace Safety" },
  { id: 185, name: "Labor Law Compliance" },
  { id: 186, name: "Compensation & Benefits" },
  { id: 187, name: "Workforce Analytics" },
  { id: 188, name: "Corporate Governance" },
  { id: 189, name: "Sustainability Practices" },
  { id: 190, name: "Corporate Social Responsibility" },
  { id: 191, name: "Ethics in Business" },
  { id: 192, name: "Cross-Cultural Communication" },
  { id: 193, name: "Global Market Strategy" },
  { id: 194, name: "International Business Law" },
  { id: 195, name: "Trade Negotiations" },
  { id: 196, name: "Outsourcing Management" },
  { id: 197, name: "Partnership Development" },
  { id: 198, name: "Franchise Operations" },
  { id: 199, name: "Luxury Brand Management" },
  { id: 200, name: "Non-Profit Management" },
  // --- Writing, Editing & Communication ---
  { id: 126, name: "Creative Writing" },
  { id: 127, name: "Copywriting" },
  { id: 128, name: "Technical Writing" },
  { id: 129, name: "Proofreading" },
  { id: 130, name: "Editing" },
  { id: 131, name: "Scriptwriting" },
  { id: 132, name: "Grant Writing" },
  { id: 133, name: "Speech Writing" },
  { id: 134, name: "Content Strategy" },
  { id: 135, name: "SEO Writing" },
  { id: 136, name: "Journalism" },
  { id: 137, name: "Blogging" },
  { id: 138, name: "Press Release Writing" },
  { id: 139, name: "Ghostwriting" },
  { id: 140, name: "Business Communication" },

  // --- Language & Translation ---
  { id: 141, name: "English Language" },
  { id: 142, name: "Spanish Language" },
  { id: 143, name: "French Language" },
  { id: 144, name: "German Language" },
  { id: 145, name: "Mandarin Chinese" },
  { id: 146, name: "Japanese Language" },
  { id: 147, name: "Korean Language" },
  { id: 148, name: "Italian Language" },
  { id: 149, name: "Portuguese Language" },
  { id: 150, name: "Arabic Language" },
  { id: 151, name: "Russian Language" },
  { id: 152, name: "Sign Language" },
  { id: 153, name: "Translation" },
  { id: 154, name: "Interpretation" },
  { id: 155, name: "Subtitling" },

  // --- Healthcare & Wellness ---
  { id: 156, name: "First Aid" },
  { id: 157, name: "CPR" },
  { id: 158, name: "Nursing" },
  { id: 159, name: "Physical Therapy" },
  { id: 160, name: "Occupational Therapy" },
  { id: 161, name: "Speech Therapy" },
  { id: 162, name: "Diet and Nutrition" },
  { id: 163, name: "Mental Health Counseling" },
  { id: 164, name: "Yoga Instruction" },
  { id: 165, name: "Personal Training" },
  { id: 166, name: "Sports Coaching" },
  { id: 167, name: "Pilates Instruction" },
  { id: 168, name: "Massage Therapy" },
  { id: 169, name: "Herbal Medicine" },
  { id: 170, name: "Acupuncture" },

  // --- Science & Research ---
  { id: 171, name: "Biology" },
  { id: 172, name: "Chemistry" },
  { id: 173, name: "Physics" },
  { id: 174, name: "Environmental Science" },
  { id: 175, name: "Geology" },
  { id: 176, name: "Astronomy" },
  { id: 177, name: "Genetics" },
  { id: 178, name: "Microbiology" },
  { id: 179, name: "Botany" },
  { id: 180, name: "Zoology" },
  { id: 181, name: "Marine Biology" },
  { id: 182, name: "Ecology" },
  { id: 183, name: "Neuroscience" },
  { id: 184, name: "Pharmacology" },
  { id: 185, name: "Forensic Science" },

  // --- Education & Training ---
  { id: 186, name: "Curriculum Development" },
  { id: 187, name: "Teaching" },
  { id: 188, name: "Tutoring" },
  { id: 189, name: "E-Learning Development" },
  { id: 190, name: "Instructional Design" },
  { id: 191, name: "Classroom Management" },
  { id: 192, name: "Special Education" },
  { id: 193, name: "Educational Technology" },
  { id: 194, name: "Public Speaking" },
  { id: 195, name: "Workshop Facilitation" },
  { id: 196, name: "Mentoring" },
  { id: 197, name: "Coaching" },
  { id: 198, name: "Exam Preparation" },
  { id: 199, name: "Academic Writing" },
  { id: 200, name: "Research Methods" },

  // --- Public Service & Safety ---
  { id: 201, name: "Law Enforcement" },
  { id: 202, name: "Firefighting" },
  { id: 203, name: "Emergency Management" },
  { id: 204, name: "Security Operations" },
  { id: 205, name: "Criminal Investigation" },
  { id: 206, name: "Cybersecurity" },
  { id: 207, name: "Disaster Relief" },
  { id: 208, name: "Community Outreach" },
  { id: 209, name: "Public Policy" },
  { id: 210, name: "Government Administration" },
  { id: 211, name: "Legal Research" },
  { id: 212, name: "Litigation" },
  { id: 213, name: "Contract Law" },
  { id: 214, name: "Mediation" },
  { id: 215, name: "Human Rights Advocacy" },

  // --- Sports & Recreation ---
  { id: 216, name: "Soccer Coaching" },
  { id: 217, name: "Basketball Coaching" },
  { id: 218, name: "Tennis Instruction" },
  { id: 219, name: "Swimming Instruction" },
  { id: 220, name: "Running Training" },
  { id: 221, name: "Cycling Coaching" },
  { id: 222, name: "Martial Arts Instruction" },
  { id: 223, name: "Climbing Instruction" },
  { id: 224, name: "Golf Instruction" },
  { id: 225, name: "Baseball Coaching" },
  { id: 226, name: "Volleyball Coaching" },
  { id: 227, name: "Table Tennis Coaching" },
  { id: 228, name: "Badminton Coaching" },
  { id: 229, name: "Archery Instruction" },
  { id: 230, name: "Skiing Instruction" },

  // --- Travel & Hospitality ---
  { id: 231, name: "Tour Guiding" },
  { id: 232, name: "Travel Planning" },
  { id: 233, name: "Hospitality Management" },
  { id: 234, name: "Event Coordination" },
  { id: 235, name: "Hotel Operations" },
  { id: 236, name: "Restaurant Management" },
  { id: 237, name: "Food Service" },
  { id: 238, name: "Bartending" },
  { id: 239, name: "Customer Service" },
  { id: 240, name: "Front Desk Operations" },
  { id: 241, name: "Housekeeping Management" },
  { id: 242, name: "Culinary Arts" },
  { id: 243, name: "Baking & Pastry Arts" },
  { id: 244, name: "Wine Tasting" },
  { id: 245, name: "Menu Design" },

  // --- Life Skills & Personal Development ---
  { id: 246, name: "Time Management" },
  { id: 247, name: "Organization Skills" },
  { id: 248, name: "Negotiation Skills" },
  { id: 249, name: "Stress Management" },
  { id: 250, name: "Emotional Intelligence" },
];
